import React from 'react';
import Layout from '../components/Layout';
import { Helmet } from 'react-helmet-async';

const PrivacyPolicy = () => {
  return (
    <>
      <Helmet>
        <title>Privacy Policy - AutoMod AI</title>
        <meta name="description" content="Read AutoMod AI's privacy policy to understand how we collect, use, and protect your personal information when using our AI-powered car customization platform." />
        <meta name="keywords" content="privacy policy, data protection, user privacy, AutoMod AI privacy, car customization privacy, automotive data security" />
      </Helmet>
      <Layout>
        <div className="container mx-auto px-4 max-w-4xl py-20">
          <div className="prose prose-invert prose-lg max-w-none space-y-8 bg-secondary/50 p-8 rounded-lg border border-accent/20">
            {/* Main Title */}
            <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-red-600 via-red-400 to-white bg-clip-text text-transparent mb-4">
              Privacy Policy
            </h1>
            
            <p className="text-accent font-semibold">Last updated: February 10, 2025</p>
            
            {/* Introduction */}
            <div className="space-y-6">
              <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
              <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" className="text-accent hover:text-accent-bright">Privacy Policy Generator</a>.</p>
            </div>

            {/* Interpretation and Definitions */}
            <h2 className="text-3xl font-bold bg-gradient-to-r from-red-600 via-red-400 to-white bg-clip-text text-transparent">
              Interpretation and Definitions
            </h2>

            <div className="border-l-4 border-accent pl-6 my-8">
              <h3 className="text-2xl font-semibold mb-4">Interpretation</h3>
              <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            </div>

            <div className="border-l-4 border-accent pl-6 my-8">
              <h3 className="text-2xl font-semibold mb-4">Definitions</h3>
              <p className="mb-4">For the purposes of this Privacy Policy:</p>
              
              <ul className="space-y-4">
                {[
                  { term: 'Account', def: 'means a unique account created for You to access our Service or parts of our Service.' },
                  { term: 'Affiliate', def: 'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.' },
                  { term: 'Company', def: '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Automod, 28 Sangam Ln, Colombo 00600.' },
                  { term: 'Cookies', def: 'are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.' },
                  { term: 'Country', def: 'refers to: Sri Lanka' },
                  { term: 'Device', def: 'means any device that can access the Service such as a computer, a cellphone or a digital tablet.' },
                  { term: 'Personal Data', def: 'is any information that relates to an identified or identifiable individual.' },
                  { term: 'Service', def: 'refers to the Website.' },
                  { term: 'Service Provider', def: 'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.' },
                  { term: 'Third-party Social Media Service', def: 'refers to any website or any social network website through which a User can log in or create an account to use the Service.' },
                  { term: 'Usage Data', def: 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' },
                  { term: 'Website', def: 'refers to Automod, accessible from https://automod.lk/' },
                  { term: 'You', def: 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.' }
                ].map((item, index) => (
                  <li key={index} className="bg-primary/40 p-6 rounded-lg border border-accent/10">
                    <p className="font-semibold text-accent mb-2">{item.term}</p>
                    <p>{item.def}</p>
                  </li>
                ))}
              </ul>
            </div>

            {/* Types of Data Collected */}
            <h2 className="text-3xl font-bold bg-gradient-to-r from-red-600 via-red-400 to-white bg-clip-text text-transparent">
              Collecting and Using Your Personal Data
            </h2>

            <div className="space-y-8">
              <h3 className="text-2xl font-semibold">Types of Data Collected</h3>
              
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Personal Data</h4>
                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Usage Data</li>
                </ul>
              </div>

              {/* Usage Data */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Usage Data</h4>
                <p>Usage Data is collected automatically when using the Service.</p>
                <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
              </div>

              {/* Third-Party Social Media Services */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Information from Third-Party Social Media Services</h4>
                <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Google</li>
                  <li>Facebook</li>
                  <li>Instagram</li>
                  <li>Twitter</li>
                  <li>LinkedIn</li>
                </ul>
                <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
                <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
              </div>

              {/* Tracking Technologies and Cookies */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Tracking Technologies and Cookies</h4>
                <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                
                <div className="space-y-4">
                  <div className="bg-primary/40 p-6 rounded-lg border border-accent/10">
                    <p className="font-semibold text-accent mb-2">Cookies or Browser Cookies</p>
                    <p>A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>
                  </div>
                  
                  <div className="bg-primary/40 p-6 rounded-lg border border-accent/10">
                    <p className="font-semibold text-accent mb-2">Web Beacons</p>
                    <p>Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</p>
                  </div>
                </div>

                <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on <a href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies" target="_blank" className="text-accent hover:text-accent-bright">TermsFeed website</a> article.</p>

                <p>We use both Session and Persistent Cookies for the purposes set out below:</p>

                <div className="space-y-4">
                  <div className="bg-primary/40 p-6 rounded-lg border border-accent/10">
                    <p className="font-semibold text-accent mb-2">Necessary / Essential Cookies</p>
                    <p>Type: Session Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                  </div>

                  <div className="bg-primary/40 p-6 rounded-lg border border-accent/10">
                    <p className="font-semibold text-accent mb-2">Cookies Policy / Notice Acceptance Cookies</p>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                  </div>

                  <div className="bg-primary/40 p-6 rounded-lg border border-accent/10">
                    <p className="font-semibold text-accent mb-2">Functionality Cookies</p>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                  </div>
                </div>

                <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
              </div>

              {/* Use of Your Personal Data */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Use of Your Personal Data</h4>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                  <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                  <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                  <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                  <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                </ul>
              </div>

              {/* Retention of Your Personal Data */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Retention of Your Personal Data</h4>
                <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer periods.</p>
              </div>

              {/* Transfer of Your Personal Data */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Transfer of Your Personal Data</h4>
                <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                <p>If You are located outside Sri Lanka and choose to provide information to Us, please note that We transfer the data, including Personal Data, to Sri Lanka and process it there.</p>
                <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
              </div>

              {/* Delete Your Personal Data */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Delete Your Personal Data</h4>
                <p>You have the right to delete or request that We assist You with deleting the Personal Data that We have collected about You.</p>
                <p>You can exercise this right by contacting Us through the contact information provided under the "Contact Us" section.</p>
              </div>

              {/* Disclosure of Your Personal Data */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Disclosure of Your Personal Data</h4>
                <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Comply with a legal obligation</li>
                  <li>Protect and defend the rights or property of the Company</li>
                  <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                  <li>Protect the personal safety of users of the Service or the public</li>
                  <li>Protect against legal liability</li>
                </ul>
              </div>

              {/* Security of Your Personal Data */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Security of Your Personal Data</h4>
                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
              </div>

              {/* Children's Privacy */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Children's Privacy</h4>
                <p>Our Service is not intended for individuals under the age of 18. We do not knowingly collect personal information from anyone under the age of 18. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 18 without verification of parental consent, We take steps to remove that information from Our servers.</p>
              </div>

              {/* Links to Other Websites */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Links to Other Websites</h4>
                <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party's link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
              </div>

              {/* Changes to this Privacy Policy */}
              <div className="space-y-6">
                <h4 className="text-xl font-semibold text-accent">Changes to this Privacy Policy</h4>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
              </div>

              {/* Contact Us section */}
              <div className="bg-primary/40 p-8 rounded-lg border border-accent/10 mt-12">
                <h2 className="text-3xl font-bold bg-gradient-to-r from-red-600 via-red-400 to-white bg-clip-text text-transparent mb-6">
                  Contact Us
                </h2>
                <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul className="space-y-4">
                  <li className="flex items-center space-x-3">
                    <span className="text-accent">•</span>
                    <span>By email: contact@automod.lk</span>
                  </li>
                  <li className="flex items-center space-x-3">
                    <span className="text-accent">•</span>
                    <span>By visiting this page on our website: <a href="https://automod.lk/contact" className="text-accent hover:text-accent-bright transition-colors" target="_blank">https://automod.lk/contact</a></span>
                  </li>
                  <li className="flex items-center space-x-3">
                    <span className="text-accent">•</span>
                    <span>By phone number: 0112 364 044</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default PrivacyPolicy; 